name: Workflow for Codecov easyclimate-python
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Set up Python 3.11
        uses: actions/setup-python@v5.3.0
        with:
          python-version: '3.11'

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Create virtual environment
        run: uv venv .venv

      - name: Install dependencies
        run: |
          source .venv/bin/activate
          uv pip install numba numpy
          uv pip install -r test_requirements.txt

      - name: Run tests and collect coverage
        run: |
          source .venv/bin/activate
          pytest --mpl --mpl-baseline-path="test/baseline_images" --cov src

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
